Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -127,42 +127,42 @@ stages:
         failTaskOnFailedTests: true
 
 
-# - stage: SonarQubeAnalysis
-#   displayName: 'Static Analysis with SonarQube'
-#   jobs:
-#   - job: SonarScan
-#     displayName: 'Run SonarQube Scan'
-#     pool:
-#       name: MyLinuxAgents
-#     steps:
-#     - task: SonarQubePrepare@6
-#       displayName: 'Prepare SonarQube Analysis'
-#       condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # <--- ADD THIS LINE
-#       inputs:
-#           SonarQube: 'sonarqube'
-#           scannerMode: 'CLI'
-#           configMode: 'manual'
-#           cliProjectKey: $(SONARQUBE_PROJECT_KEY)
-#           cliProjectName: 'temitope'
-#           extraProperties: |
-#               sonar.sources=src
-#               sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**
+- stage: SonarQubeAnalysis
+  displayName: 'Static Analysis with SonarQube'
+  jobs:
+  - job: SonarScan
+    displayName: 'Run SonarQube Scan'
+    pool:
+      name: MyLinuxAgents
+    steps:
+    - task: SonarQubePrepare@6
+      displayName: 'Prepare SonarQube Analysis'
+      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # <--- ADD THIS LINE
+      inputs:
+          SonarQube: 'sonarqube'
+          scannerMode: 'CLI'
+          configMode: 'manual'
+          cliProjectKey: $(SONARQUBE_PROJECT_KEY)
+          cliProjectName: 'temitope'
+          extraProperties: |
+              sonar.sources=src
+              sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**
             
-#     - task: SonarQubeAnalyze@6
-#       displayName: 'Run SonarQube Analysis'
-#       condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 
+    - task: SonarQubeAnalyze@6
+      displayName: 'Run SonarQube Analysis'
+      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 
       
-#     - task: SonarQubePublish@6
-#       displayName: 'Publish SonarQube Results and Wait for Quality Gate'
-#       inputs:
-#         pollingTimeoutSec: '300' 
-#       condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # This ensures the SonarQube publish step runs only for non-PR builds
+    - task: SonarQubePublish@6
+      displayName: 'Publish SonarQube Results and Wait for Quality Gate'
+      inputs:
+        pollingTimeoutSec: '300' 
+      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # This ensures the SonarQube publish step runs only for non-PR builds
      
-#     - task: SonarQubePublish@6
-#       displayName: 'Publish SonarQube Results and Wait for Quality Gate'
-#       inputs:
-#         pollingTimeoutSec: '300' 
-#       condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # This ensures the SonarQube publish step runs only for non-PR builds
+    - task: SonarQubePublish@6
+      displayName: 'Publish SonarQube Results and Wait for Quality Gate'
+      inputs:
+        pollingTimeoutSec: '300' 
+      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # This ensures the SonarQube publish step runs only for non-PR builds
 
 
 - stage: BuildAndScanDockerImage
@@ -197,16 +197,16 @@ stages:
         buildContext: '$(Build.SourcesDirectory)' 
 
      # Generate SBOM with Syft
-    - bash: |
-        echo "Generating SBOM for ${DOCKER_IMAGE_FULL_NAME} with Syft..."
-        syft "${DOCKER_IMAGE_FULL_NAME}" -o spdx-json > "$(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)"
-        if [ $? -ne 0 ]; then
-          echo "##vso[task.logissue type=error]Syft SBOM generation failed!"
-          exit 1
-        fi
-        echo "SBOM generated: $(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)"
-      displayName: 'Generate SBOM with Syft'
-      workingDirectory: '$(Build.SourcesDirectory)'
+    # - bash: |
+    #     echo "Generating SBOM for ${DOCKER_IMAGE_FULL_NAME} with Syft..."
+    #     syft "${DOCKER_IMAGE_FULL_NAME}" -o spdx-json > "$(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)"
+    #     if [ $? -ne 0 ]; then
+    #       echo "##vso[task.logissue type=error]Syft SBOM generation failed!"
+    #       exit 1
+    #     fi
+    #     echo "SBOM generated: $(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)"
+    #   displayName: 'Generate SBOM with Syft'
+    #   workingDirectory: '$(Build.SourcesDirectory)'
     
     # Using trivy to generate SBOM
     - bash: |
@@ -221,17 +221,17 @@ stages:
       workingDirectory: '$(Build.SourcesDirectory)'
 
     # Grype SBOM Scan 
-    - bash: |
-        echo "Scanning SBOM for vulnerabilities with Grype..."
-        grype sbom:"$(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)" --fail-on critical
-        if [ $? -ne 0 ]; then
-          echo "##vso[task.logissue type=error]Grype scan found critical vulnerabilities in SBOM! Build failed."
-          exit 1
-        else
-          echo "Grype scan passed. No critical vulnerabilities found."
-        fi
-      displayName: 'Run Grype SBOM Scan'
-      workingDirectory: '$(Build.SourcesDirectory)'
+    # - bash: |
+    #     echo "Scanning SBOM for vulnerabilities with Grype..."
+    #     grype sbom:"$(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)" --fail-on critical
+    #     if [ $? -ne 0 ]; then
+    #       echo "##vso[task.logissue type=error]Grype scan found critical vulnerabilities in SBOM! Build failed."
+    #       exit 1
+    #     else
+    #       echo "Grype scan passed. No critical vulnerabilities found."
+    #     fi
+    #   displayName: 'Run Grype SBOM Scan'
+    #   workingDirectory: '$(Build.SourcesDirectory)'
 
      # Run Trivy SBOM Scan
     - bash: |
@@ -248,11 +248,11 @@ stages:
       workingDirectory: '$(Build.SourcesDirectory)'
 
      # Publish SBOM as a build artifact
-    - task: PublishBuildArtifacts@1
-      displayName: 'Publish SBOM Artifact'
-      inputs:
-        pathToPublish: '$(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)'
-        artifactName: 'SBOMs'
+    # - task: PublishBuildArtifacts@1
+    #   displayName: 'Publish SBOM Artifact'
+    #   inputs:
+    #     pathToPublish: '$(Build.SourcesDirectory)/$(SBOM_SYFT_FILE_NAME)'
+    #     artifactName: 'SBOMs'
 
     # Publish Trivy SBOM as a build artifact
     - task: PublishBuildArtifacts@1
